env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    tsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: 
  react/jsx-props-no-spreading: off
  import/prefer-default-export: off
  no-shadow: off
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  react/react-in-jsx-scope: off
  no-unused-vars: off
  no-console: 0
  react/display-name: off
  jsx-a11y/click-events-have-key-events: off
  no-use-before-define: off
  jsx-a11y/no-noninteractive-element-interactions: ['error',{handlers: ['onClick','onMouseDown','onMouseUp','onKeyPress','onKeyDown','onKeyUp',],},]
  react/jsx-filename-extension: [2, { 'extensions': ['.ts', '.tsx'] }]
  no-param-reassign: ['error', { props: false }]
  react/function-component-definition: [2,{namedComponents: "arrow-function",unnamedComponents: "arrow-function",},]

